key: "group_case_study"
title: "Case Study"
location:
  -
    - { param: "post_type", operator: "==", value: "case_study" }
menu_order: 0
position: "normal"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ["the_content"]
fields:
    -
        key:  "field_case_image"
        label:  "Image"
        name:  "case_image"
        type:  "image"
        instructions:  ""
        required:  1
        conditional_logic:  0,
        wrapper:  { width:  "34", class:  "", id:  "" }
        return_format:  "array"
        preview_size:  "thumbnail"
        library:  "all"
        min_width:  ""
        min_height:  ""
        min_size:  ""
        max_width:  ""
        max_height:  ""
        max_size:  ""
        mime_types:  ""
    -
        key: "field_case_details"
        label: "Details"
        name: "case_details"
        type: "repeater"
        instructions:
        required: 1
        conditional_logic: 0
        wrapper: { width: "", class: "", id: "" }
        collapsed:
        min: 1
        max: 0
        layout: "block"
        button_label: "Add Row"
        sub_fields:
            -
                key: "field_case_details_title"
                label: "Title"
                name: "case_details_title"
                type: "text"
                instructions:
                required: 1
                conditional_logic: 0
                wrapper: { width: "50", class: "", id: "" }
            -
                key: "field_case_details_content"
                label: "Content"
                name: "case_details_content"
                type: "wysiwyg"
                instructions:
                required: 1
                conditional_logic: 0
                wrapper: { width: "50", class: "", id: "" }
                tabs: "all"
                toolbar: "basic"
                media_upload: 0
    -
        key:  "field_testimonial_author"
        label:  "Testimonial Author"
        name:  "testimonial_author"
        type:  "text"
        instructions:  ""
        required:  1
        conditional_logic:  0,
        wrapper:  { width:  "33", class:  "", id:  "" }
    -
        key:  "field_testimonial_content"
        label:  "Testimonial Content"
        name:  "testimonial_content"
        type:  "textarea"
        instructions:  ""
        required:  1
        conditional_logic:  0,
        wrapper:  { width:  "33", class:  "", id:  "" }
    -
        key:  "field_testimonial_logo"
        label:  "Testimonial Logo"
        name:  "testimonial_logo"
        type:  "image"
        instructions:  ""
        required:  1
        conditional_logic:  0,
        wrapper:  { width:  "34", class:  "", id:  "" }
        return_format:  "array"
        preview_size:  "thumbnail"
        library:  "all"
        min_width:  ""
        min_height:  ""
        min_size:  ""
        max_width:  ""
        max_height:  ""
        max_size:  ""
        mime_types:  ""