key: "group_header"
title: "Header"
location:
  -
    - { param: "post_type", operator: "==", value: "post" }
  -
    - { param: "post_type", operator: "==", value: "page" }
menu_order: 1
position: "side"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ""
fields:
  -
    key:  "field_heading"
    label:  "Heading"
    name:  "header_heading"
    type:  "text"
    instructions:  "Defaults to title"
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_background"
    label:  "Background"
    name:  "header_background"
    type:  "file"
    return_format: "array"
    instructions:  "Defaults theme settings image."
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0