key: "group_page_builder"
title: "Page Builder"
location:
  -
    - { param: "post_type", operator: "==", value: "page" }
menu_order: 0
position: "acf_after_title"
style: "default"
label_placement: "top"
instruction_placement: "label"
hide_on_screen: ["the_content"]
active: 1
description:
fields:
    -
        key: "field_builder"
        label: "Content Builder"
        name: "content_builder"
        type: "flexible_content"
        instructions:
        required: 0
        wrapper: { width: "", class: "", id: "" }
        button_label: "Add Row"
        layouts:
            -
                key: "layout_basic"
                name: "basic_content"
                label: "Basic Content"
                instructions: "Basic content on a whate background"
                display: "block"
                sub_fields:
                    -
                        key: "field_drop_caps_letter"
                        label: "Drop Caps Letter"
                        name: "drop_caps_letter"
                        type: "text"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                    -
                        key: "field_drop_caps_content"
                        label: "Drop Caps Content"
                        name: "drop_caps_content"
                        type: "textarea"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                    -
                        key: "field_basic_content"
                        label: "Content"
                        name: "content"
                        type: "wysiwyg"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                        tabs: "all"
                        toolbar: "full"
                        media_upload: 1
            -
                key: "layout_video"
                name: "video_content"
                label: "Video"
                instructions: "large image and text with lightbox video"
                display: "block"
                sub_fields:
                    -
                        key: "field_video_image"
                        label: "Video Image"
                        name: "video_background"
                        type: "image"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                        default_value:
                        return_format:  "array"
                        preview_size:  "thumbnail"
                        library:  "all"
                        min_width:  ""
                        min_height:  ""
                        min_size:  ""
                        max_width:  ""
                        max_height:  ""
                        max_size:  ""
                        mime_types:  ""
                    -
                        key: "field_video"
                        label: "Video URL"
                        name: "video_embed"
                        type: "url"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                        default_value:
                    -
                        key: "field_video_content"
                        label: "Content"
                        name: "video_content"
                        type: "wysiwyg"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "", class: "", id: "" }
                        default_value:
                        tabs: "all"
                        toolbar: "full"
                        media_upload: 0
            -
                key: "layout_navigation"
                name: "navigation_content"
                label: "Navigation Row"
                instructions: "Three columns. One with content and the other two with navigation list"
                display: "block"
                sub_fields:
                    -
                        key: "field_nvaigation_first_heading"
                        label: "First heading"
                        name: "first_heading"
                        type: "text"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                    -
                        key: "field_nvaigation_first_content"
                        label: "First column content"
                        name: "first_content"
                        type: "wysiwyg"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                        default_value:
                        tabs: "all"
                        toolbar: "basic"
                        media_upload: 0
                    -
                        key: "field_nvaigation_second_heading"
                        label: "Second heading"
                        name: "second_heading"
                        type: "text"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                    -
                        key: "field_nvaigation_second_links"
                        label: "Second column links"
                        name: "second_links"
                        type: "repeater"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                        collapsed:
                        min: 1
                        max: 0
                        layout: block
                        button_label: Add Row
                        sub_fields:
                          -
                            key:  "field_navigation_second_link_title"
                            label:  "text"
                            name:  "second_title"
                            type:  "text"
                            instructions:  ""
                            required:  1,
                            conditional_logic:  0,
                            wrapper:  { width:  "50", class:  "", id:  "" }
                          -
                            key:  "field_navigation_second_link_link"
                            label:  "url"
                            name:  "second_url"
                            type:  "url"
                            instructions:  ""
                            required:  1,
                            conditional_logic:  0,
                            wrapper:  { width:  "50", class:  "", id:  "" }
                    -
                        key: "field_nvaigation_third_heading"
                        label: "Third heading"
                        name: "third_heading"
                        type: "text"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                    -
                        key: "field_nvaigation_third_links"
                        label: "Third column links"
                        name: "third_links"
                        type: "repeater"
                        instructions:
                        required: 1
                        conditional_logic: 0
                        wrapper: { width: "50", class: "", id: "" }
                        collapsed:
                        min: 1
                        max: 0
                        layout: block
                        button_label: Add Row
                        sub_fields:
                          -
                            key:  "field_navigation_third_link_title"
                            label:  "text"
                            name:  "third_title"
                            type:  "text"
                            instructions:  ""
                            required:  1,
                            conditional_logic:  0,
                            wrapper:  { width:  "50", class:  "", id:  "" }
                          -
                            key:  "field_navigation_third_link_link"
                            label:  "url"
                            name:  "third_url"
                            type:  "url"
                            instructions:  ""
                            required:  1,
                            conditional_logic:  0,
                            wrapper:  { width:  "50", class:  "", id:  "" }
