key: "group_theme_options"
title: "Theme Options"
location:
  -
    - { param: "options_page", operator: "==", value: "acf-options-theme-options" }
menu_order: 0
position: "normal"
style: "default"
label_placement: "top"
instruction_placement: label
hide_on_screen: ""
fields:
  -
    key:  "field_google_analytics"
    label:  "Google Analytics ID"
    name:  "google_analytics_id"
    type:  "text"
    instructions:  ""
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_publisher_key"
    label:  "Share This Publisher Key"
    name:  "sharethis_key"
    type:  "text"
    instructions:  "Share this will not work unless a publisher key is set"
    required:  0,
    conditional_logic:  0,
    wrapper:  { width:  "", class:  "", id:  "" }
    default_value:  ""
    placeholder:  ""
    prepend:  ""
    append:  ""
    maxlength:  ""
    readonly:  0,
    disabled:  0
  -
    key:  "field_logo"
    label:  "Logo"
    name:  "logo"
    type:  "image"
    instructions:  ""
    required:  1
    conditional_logic:  0
    wrapper:  {width:  "33", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_mobile_logo"
    label:  "Mobile Logo"
    name:  "mobile_logo"
    type:  "image"
    instructions:  ""
    required:  1
    conditional_logic:  0
    wrapper:  { width:  "33", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_favicon"
    label:  "Favicon"
    name:  "favicon"
    type:  "image"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "34", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
  -
    key:  "field_default_heading_background"
    label:  "Default Header Background"
    name:  "default_header_background"
    type:  "image"
    instructions:  ""
    required:  0
    conditional_logic:  0
    wrapper:  { width:  "", class:  "", id:  "" }
    return_format:  "array"
    preview_size:  "thumbnail"
    library:  "all"
    min_width:  ""
    min_height:  ""
    min_size:  ""
    max_width:  ""
    max_height:  ""
    max_size:  ""
    mime_types:  ""
